services:
  next-stream-app:
    container_name: next-app
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        NODE_ENV: ${NODE_ENV}
        NEXT_PUBLIC_BASE_URL: ${NEXT_PUBLIC_BASE_URL}
    restart: always
    ports:
      - 3000:3000
    networks:
      - next_network

  # Add more containers below (nginx, postgres, etc.)

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  next_network:
    external: true
